
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PokeroleUI2.Databases
{

using System;
    using System.Collections.Generic;
    
public partial class AttributesCore
{

    public long Id { get; set; }

    public long HP { get; set; }

    public long STR { get; set; }

    public long STRMAX { get; set; }

    public long DEX { get; set; }

    public long DEXMAX { get; set; }

    public long VIT { get; set; }

    public long VITMAX { get; set; }

    public long SPE { get; set; }

    public long SPEMAX { get; set; }

    public long INS { get; set; }

    public long INSMAX { get; set; }

    public long HEIGHT { get; set; }

    public long WEIGHT { get; set; }

}

}
