//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeroleUI2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class DexCore
    {
        public long Id { get; set; }
        public string DEXID { get; set; }
        public string NAME { get; set; }
        public string TYPE1 { get; set; }
        public string TYPE2 { get; set; }
        public string RANK { get; set; }
        public Nullable<long> EXCLUDE { get; set; }
    }
}
