//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeroleUI2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagePath
    {
        public long Id { get; set; }
        public string DexID { get; set; }
        public string FullPaths { get; set; }
        public string ThumbPaths { get; set; }
    }
}
