//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeroleUI2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovesCore
    {
        public long Id { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public string CATEGORY { get; set; }
        public string POWER { get; set; }
        public string POWERSTAT { get; set; }
        public string ACCURACYSTAT1 { get; set; }
        public string ACCURACYSTAT2 { get; set; }
        public string TARGET { get; set; }
        public string EFFECT { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
