

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PokeroleUI2.Databases
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PokedexDBEntities : DbContext
{
    public PokedexDBEntities()
        : base("name=PokedexDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AbilitiesCore> AbilitiesCores { get; set; }

    public virtual DbSet<AttributesCore> AttributesCores { get; set; }

    public virtual DbSet<DexCore> DexCores { get; set; }

    public virtual DbSet<LearnsetsCore> LearnsetsCores { get; set; }

    public virtual DbSet<MovesCore> MovesCores { get; set; }

    public virtual DbSet<ImagePath> ImagePaths { get; set; }

    public virtual DbSet<AbilitiesDesc> AbilitiesDescs { get; set; }

}

}

